export const styles = {
    page: {
        minHeight: "100vh",
        backgroundColor: "#f9ede8",
    },
    main: {
        maxWidth: "1150px",
        margin: "0 auto",
        padding: "2rem",
    },
    card: {
        backgroundColor: "#edcfcf",
        borderRadius: "12px",
        padding: "1.25rem",
        boxShadow: "0 2px 10px rgba(0,0,0,0.08)",
    },
    innerCard: {
        backgroundColor: "#f7e2e2",
        borderRadius: "12px",
        padding: "1rem",
    },
    primaryButton: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "8px",
        padding: "0.75rem 1rem",
        backgroundColor: "#95424d",
        color: "#fff",
        border: "1px solid #95424d",
        borderRadius: "10px",
        cursor: "pointer",
        textDecoration: "none",
        fontWeight: "600",
        boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
        transition: "0.2s ease",
    },
    secondaryButton: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "8px",
        padding: "0.75rem 1rem",
        backgroundColor: "#f7e2e2",
        color: "#5a0c1f",
        border: "1px solid #d8c2c2",
        borderRadius: "10px",
        cursor: "pointer",
        textDecoration: "none",
        fontWeight: "600",
        boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
        transition: "0.2s ease",
    },
    input: {
        width: "100%",
        padding: "0.85rem",
        borderRadius: "8px",
        border: "1px solid #d8c2c2",
        boxSizing: "border-box",
        backgroundColor: "#fff",
        color: "#000",
        marginTop: "0.35rem",
    },
    textarea: {
        width: "100%",
        padding: "0.85rem",
        borderRadius: "8px",
        border: "1px solid #d8c2c2",
        boxSizing: "border-box",
        backgroundColor: "#fff",
        color: "#000",
        marginTop: "0.35rem",
        minHeight: "140px",
        resize: "vertical",
    },
    tag: {
        padding: "0.4rem 0.8rem",
        backgroundColor: "#f7e2e2",
        borderRadius: "999px",
        fontSize: "0.85rem",
        color: "#5a0c1f",
        display: "inline-block",
    },
    linkButton: {
        display: "inline-flex",
        alignItems: "center",
        gap: "8px",
        padding: "0.75rem 1rem",
        backgroundColor: "#f7e2e2",
        color: "#5a0c1f",
        border: "1px solid #d8c2c2",
        borderRadius: "10px",
        textDecoration: "none",
        fontWeight: "600",
        boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
        transition: "0.2s ease",
    }
};